// Whisper がサポートする言語コード一覧。
// label は各言語のネイティブ名 (autonym) — UI 言語に関わらず母語話者が探せるようにするため。
// 利用頻度の高い言語を先頭に置き、以降はコード順。

export interface LanguageOption {
  code: string;
  label: string;
}

// よく使う言語 (先頭に配置)
const COMMON: LanguageOption[] = [
  { code: "ja", label: "日本語" },
  { code: "en", label: "English" },
  { code: "zh", label: "中文" },
  { code: "ko", label: "한국어" },
];

// その他の言語 (コード順)
const OTHERS: LanguageOption[] = [
  { code: "af", label: "Afrikaans" },
  { code: "am", label: "አማርኛ" },
  { code: "ar", label: "العربية" },
  { code: "as", label: "অসমীয়া" },
  { code: "az", label: "Azərbaycan" },
  { code: "ba", label: "Башҡортса" },
  { code: "be", label: "Беларуская" },
  { code: "bg", label: "Български" },
  { code: "bn", label: "বাংলা" },
  { code: "bo", label: "བོད་སྐད" },
  { code: "br", label: "Brezhoneg" },
  { code: "bs", label: "Bosanski" },
  { code: "ca", label: "Català" },
  { code: "cs", label: "Čeština" },
  { code: "cy", label: "Cymraeg" },
  { code: "da", label: "Dansk" },
  { code: "de", label: "Deutsch" },
  { code: "el", label: "Ελληνικά" },
  { code: "es", label: "Español" },
  { code: "et", label: "Eesti" },
  { code: "eu", label: "Euskara" },
  { code: "fa", label: "فارسی" },
  { code: "fi", label: "Suomi" },
  { code: "fo", label: "Føroyskt" },
  { code: "fr", label: "Français" },
  { code: "gl", label: "Galego" },
  { code: "gu", label: "ગુજરાતી" },
  { code: "ha", label: "Hausa" },
  { code: "haw", label: "ʻŌlelo Hawaiʻi" },
  { code: "he", label: "עברית" },
  { code: "hi", label: "हिन्दी" },
  { code: "hr", label: "Hrvatski" },
  { code: "ht", label: "Kreyòl ayisyen" },
  { code: "hu", label: "Magyar" },
  { code: "hy", label: "Հայերեն" },
  { code: "id", label: "Bahasa Indonesia" },
  { code: "is", label: "Íslenska" },
  { code: "it", label: "Italiano" },
  { code: "jw", label: "Basa Jawa" },
  { code: "ka", label: "ქართული" },
  { code: "kk", label: "Қазақ" },
  { code: "km", label: "ខ្មែរ" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "la", label: "Latina" },
  { code: "lb", label: "Lëtzebuergesch" },
  { code: "ln", label: "Lingála" },
  { code: "lo", label: "ລາວ" },
  { code: "lt", label: "Lietuvių" },
  { code: "lv", label: "Latviešu" },
  { code: "mg", label: "Malagasy" },
  { code: "mi", label: "Māori" },
  { code: "mk", label: "Македонски" },
  { code: "ml", label: "മലയാളം" },
  { code: "mn", label: "Монгол" },
  { code: "mr", label: "मराठी" },
  { code: "ms", label: "Bahasa Melayu" },
  { code: "mt", label: "Malti" },
  { code: "my", label: "မြန်မာ" },
  { code: "ne", label: "नेपाली" },
  { code: "nl", label: "Nederlands" },
  { code: "nn", label: "Norsk nynorsk" },
  { code: "no", label: "Norsk" },
  { code: "oc", label: "Occitan" },
  { code: "pa", label: "ਪੰਜਾਬੀ" },
  { code: "pl", label: "Polski" },
  { code: "ps", label: "پښتو" },
  { code: "pt", label: "Português" },
  { code: "ro", label: "Română" },
  { code: "ru", label: "Русский" },
  { code: "sa", label: "संस्कृतम्" },
  { code: "sd", label: "سنڌي" },
  { code: "si", label: "සිංහල" },
  { code: "sk", label: "Slovenčina" },
  { code: "sl", label: "Slovenščina" },
  { code: "sn", label: "ChiShona" },
  { code: "so", label: "Soomaali" },
  { code: "sq", label: "Shqip" },
  { code: "sr", label: "Српски" },
  { code: "su", label: "Basa Sunda" },
  { code: "sv", label: "Svenska" },
  { code: "sw", label: "Kiswahili" },
  { code: "ta", label: "தமிழ்" },
  { code: "te", label: "తెలుగు" },
  { code: "tg", label: "Тоҷикӣ" },
  { code: "th", label: "ไทย" },
  { code: "tk", label: "Türkmen" },
  { code: "tl", label: "Tagalog" },
  { code: "tr", label: "Türkçe" },
  { code: "tt", label: "Татарча" },
  { code: "uk", label: "Українська" },
  { code: "ur", label: "اردو" },
  { code: "uz", label: "Oʻzbek" },
  { code: "vi", label: "Tiếng Việt" },
  { code: "yi", label: "ייִדיש" },
  { code: "yo", label: "Yorùbá" },
  { code: "yue", label: "粵語" },
];

export const LANGUAGES: LanguageOption[] = [...COMMON, ...OTHERS];
